import TurtleInTheCity

'''
Scene.:
.DrawRoofedHouse(size)
.DrawFlet(size)
.DrawSun(size)
.DrawTree(size)
.DrawCar(size, color(optional))
.DrawCloud(size, outerColor(optional), innerColor(optional))
.MoveUp(pixels)
.MoveDown(pixels)
.MoveRight(pixels)
.MoveLeft(pixels)
.SetSpeed(0-10)
.ClearScreen()
.Delay(seconds)
'''

if __name__ == '__main__':
    Scene = TurtleInTheCity.Drawer()
    Scene.SetSpeed(0)
    Scene.MoveLeft(370)
    Scene.MoveDown(310)
    Scene.DrawRoofedHouse(75)
    Scene.MoveRight(100)
    Scene.DrawFlat(75)
    Scene.MoveRight(100)
    Scene.DrawCar(0.75,)
    Scene.MoveRight(150)
    Scene.DrawTree(40)
    Scene.MoveRight(20)
    Scene.MoveUp(500)
    Scene.DrawSun(75)
    Scene.MoveLeft(125)
    Scene.DrawCloud(125)
    Scene.MoveLeft(125)
    Scene.DrawCloud(75)
    Scene.RenderSVG('Example')
    input()
